# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: iOS Developer
description: "iOS Developer, love to create cool things"
keywords: "Apple,iOS,iPhone,games"
url: http://pawankumar.cf
baseurl: ""

google_analytics: UA-52446115-1
repo: http://github.com/pawanline/end2end
disqus_shortname: ""
disqus_site_shortname: ""

# Author settings
author:
  name: Pawan Kumar
  job: iOS Developer
  bio: "A Nature lover.A Programmer.An Extrovert..Bookhaolic . and finally take music as a drug."
  thumb: /images/author.jpg
  email: pawanline@gmail.com
  url: https://pawankumar.cf/
  github: https://github.com/pawanline
  twitter: https://twitter.com/pawanLine
  facebook: https://www.facebook.com/profile.php?id=100004177570711
  linkedin: https://www.linkedin.com/in/pawan-kumar-430951111/

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
